#!/usr/bin/env python
"""
Management utility for the QueueLess backend.

This script initializes the Django environment and delegates
command‑line arguments to Django's command execution framework. It
mimics the default ``manage.py`` generated by ``django-admin`` and
assumes that the ``DJANGO_SETTINGS_MODULE`` environment variable
points at ``queueless_backend.settings``. If you need to customise
behaviour (e.g. for testing or production deployments) you can
override the environment variable before invoking this script.
"""

import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
    try:
        # Import here to ensure Django is available. If import fails
        # we'll raise an informative error below.
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()