# Generated by Django 4.2.28 on 2026-02-23 15:22

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Tunisia', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#1e88e5', max_length=7)),
                ('secondary_color', models.CharField(default='#4caf50', max_length=7)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'db_table': 'clinics',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('total_tickets', models.IntegerField(default=0)),
                ('waiting', models.IntegerField(default=0)),
                ('called', models.IntegerField(default=0)),
                ('serving', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('cancelled', models.IntegerField(default=0)),
                ('no_show', models.IntegerField(default=0)),
                ('avg_wait_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_service_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_wait_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='core.clinic')),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
                'db_table': 'queues',
                'ordering': ['clinic__name', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(default=15)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.clinic')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['clinic', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=10)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='WAITING', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('position', models.IntegerField()),
                ('estimated_wait_time', models.IntegerField(default=0)),
                ('is_walkin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('serving_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_tickets', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.clinic')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.queue')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_tickets', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.service')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['queue', 'position'],
            },
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('QUEUE_OPENED', 'Queue opened'), ('QUEUE_CLOSED', 'Queue closed'), ('TICKET_CREATED', 'Ticket created'), ('TICKET_CALLED', 'Ticket called'), ('TICKET_SERVING', 'Ticket serving'), ('TICKET_COMPLETED', 'Ticket completed'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('TICKET_NO_SHOW', 'Ticket no show'), ('TICKET_UPDATED', 'Ticket updated')], max_length=30)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.queue')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Queue Event',
                'verbose_name_plural': 'Queue Events',
                'db_table': 'queue_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push')], max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.ticket')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operating_hours', models.JSONField(default=core.models.default_operating_hours)),
                ('max_capacity', models.IntegerField(default=50)),
                ('allow_walkins', models.BooleanField(default=True)),
                ('allow_online_joining', models.BooleanField(default=True)),
                ('auto_call_next', models.BooleanField(default=False)),
                ('estimated_service_time', models.IntegerField(default=15)),
                ('warning_threshold', models.IntegerField(default=80)),
                ('closed_message', models.TextField(blank=True, null=True)),
                ('enable_sms', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('reminder_before_minutes', models.IntegerField(default=10)),
                ('ready_notification', models.BooleanField(default=True)),
                ('missed_turn_notification', models.BooleanField(default=True)),
                ('show_estimated_wait_time', models.BooleanField(default=True)),
                ('show_queue_position', models.BooleanField(default=True)),
                ('show_people_ahead', models.BooleanField(default=True)),
                ('display_languages', models.JSONField(default=list)),
                ('custom_welcome_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.clinic')),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
                'db_table': 'clinic_settings',
            },
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['slug'], name='idx_clinics_slug'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_active'], name='idx_clinics_is_active'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['queue'], name='idx_tickets_queue_id'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['clinic'], name='idx_tickets_clinic_id'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='idx_tickets_ticket_number'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='idx_tickets_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['queue', 'position'], name='idx_tickets_position'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='idx_tickets_created_at'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['clinic'], name='idx_services_clinic_id'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='idx_services_is_active'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['clinic', 'display_order'], name='idx_services_display_order'),
        ),
        migrations.AddIndex(
            model_name='queueevent',
            index=models.Index(fields=['queue'], name='idx_queue_events_queue_id'),
        ),
        migrations.AddIndex(
            model_name='queueevent',
            index=models.Index(fields=['ticket'], name='idx_queue_events_ticket_id'),
        ),
        migrations.AddIndex(
            model_name='queueevent',
            index=models.Index(fields=['timestamp'], name='idx_queue_events_timestamp'),
        ),
        migrations.AddIndex(
            model_name='queueevent',
            index=models.Index(fields=['event_type'], name='idx_queue_events_event_type'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['clinic'], name='idx_queues_clinic_id'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['date'], name='idx_queues_date'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['is_active'], name='idx_queues_is_active'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['clinic', 'date'], name='idx_queues_clinic_date'),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('clinic', 'date')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['ticket'], name='idx_notifications_ticket_id'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='idx_notifications_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='idx_notifications_type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='idx_notifications_sent_at'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['clinic'], name='idx_users_clinic_id'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_users_is_active'),
        ),
    ]
